### ISSUE TITLE
Missing rules directory?

### ISSUE THREAD

**Issue by glenveegee** [krzysztof-grzybek/tslint-plugin-cypress#1]
After installing tslint-plugin-cypress and running tslint with your example command I get the following error:

Could not find custom rule directory: ./dist

Looks like the dist directory defined here 
```
node_modules/tslint-plugin-cypress/tslint-cypress.json
{
    "rulesDirectory": "./dist",
    "rules": {
        "no-chainable-assignment": true,
        "no-chainable-arguments": true
    }
}
```
Causes the error. If I manually create a dist folder in the tslint-plugin-cypress package everything works fine

**Comment by krzysztof-grzybek** [comment]
Thank You for reporting! Indeed, I didn't publish `dist` folder by accident in version `1.0.3`. Really sorry for that. It should work fine in `1.0.4`
